apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-postgres3
  namespace: debezium-example
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  config:
    database.hostname: postgres-source3
    database.port: 5432
    database.user: postgres
    database.password: postgres
    database.dbname: demo_db3
    topic.prefix: source_pg3
    schema.history.internal.kafka.bootstrap.servers: debezium-cluster-kafka-bootstrap.debezium-example.svc:9092
# TODO:
# - Set wal_level to logical in source pg
# - Set shared_preload_libraries to decoderbufs