apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: debezium-example
  labels:
    app: pgadmin
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: http
  selector:
    app: pgadmin