apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-source3-initdb
  namespace: debezium-example
data:
  db.sql: |
    -- Create an authors table
    CREATE TABLE authors (
        author_id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(150) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Create a posts table
    CREATE TABLE posts (
        post_id SERIAL PRIMARY KEY,
        author_id INT REFERENCES authors(author_id) ON DELETE CASCADE,
        title VARCHAR(255) NOT NULL,
        content TEXT NOT NULL,
        published_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Create a comments table
    CREATE TABLE comments (
        comment_id SERIAL PRIMARY KEY,
        post_id INT REFERENCES posts(post_id) ON DELETE CASCADE,
        author_name VARCHAR(100) NOT NULL,
        comment_text TEXT NOT NULL,
        commented_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Insert some dummy authors
    INSERT INTO authors (name, email) VALUES 
    ('Alice', 'alice@blog.com'),
    ('Bob', 'bob@blog.com');

    -- Insert some dummy posts
    INSERT INTO posts (author_id, title, content) VALUES 
    (1, 'Introduction to PostgreSQL', 'PostgreSQL is a powerful open-source database.'),
    (2, 'Why Use SQL?', 'SQL is essential for managing relational databases.');

    -- Insert some dummy comments
    INSERT INTO comments (post_id, author_name, comment_text) VALUES 
    (1, 'Charlie', 'Great post!'),
    (2, 'David', 'This is very informative.');


