---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-source1-pvc
  namespace: debezium-example
  labels:
    app: postgres-source1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-source1
  namespace: debezium-example
spec:
  selector:
    matchLabels:
      app: postgres-source1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-source1
    spec:
      containers:
      - image: postgres:16.6-alpine3.20
        name: postgres-source1
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: demo_db1
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-source1-storage
          mountPath: /var/lib/postgresql/data
        - name: postgres-source1-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-source1-storage
        persistentVolumeClaim:
          claimName: postgres-source1-pvc
      - name: postgres-source1-initdb
        configMap:
          name: postgres-source1-initdb
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-source1
  namespace: debezium-example
spec:
  ports:
  - port: 5432
    targetPort: postgres
  selector:
    app: postgres-source1